services:
  docusaurus:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: docusaurus
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - proxy-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.docusaurus.rule=Host(`docs.localhost`)
      - traefik.http.routers.docusaurus.entrypoints=web
      # - traefik.http.services.docusaurus.loadbalancer.server.port=80
      - traefik.docker.network=proxy-net
    depends_on:
      - traefik

  traefik:
    image: traefik
    container_name: traefik-web-services
    deploy:
      resources:
        limits:
          memory: 512m
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge