server {
    # Kita kunci Nginx di port 8080
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Mencegah error 404 saat refresh halaman
    location / {
        try_files $uri $uri/ /index.html;
    }
}